from dbhandler import DbHandler

class Browser:
	'Class for traversing the browser structure and controlling local media playback'



	def __init__(self):
		self.dbh = DbHandler()
		self.dbh.initmetadata()

class BrowserNode:
	'Class representing each level (node) of the browser'

	# items: a list of strings, each of which becomes a selectable item provided by the Browser; can be generated by performing a db query using filter
	# child: a child BrowserNode
	# filter: a db filter that can be passed in to query the db and autopopulate items
	def __init__(self, items, child, filter = []):
		self.child = child
		if not filter:
			
